-- ============================================================
--  FILE: database_setup.sql
--  FIXED: Foreign key constraint errors resolved
--  Run via phpMyAdmin → Import, or:
--       mysql -u root -p < database_setup.sql
-- ============================================================

-- Disable FK checks during import to avoid ordering errors
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

-- ── Create & select database ───────────────────────────────
CREATE DATABASE IF NOT EXISTS ibbul_library
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE ibbul_library;

-- ── Drop tables if they exist (clean slate) ────────────────
DROP TABLE IF EXISTS digital_access_log;
DROP TABLE IF EXISTS fines;
DROP TABLE IF EXISTS announcements;
DROP TABLE IF EXISTS reservations;
DROP TABLE IF EXISTS loans;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS matric_serials;
DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS faculties;

-- ════════════════════════════════════════════════════════════
--  TABLE DEFINITIONS
-- ════════════════════════════════════════════════════════════

-- ── 1. FACULTIES ───────────────────────────────────────────
CREATE TABLE faculties (
    id         INT          NOT NULL AUTO_INCREMENT,
    code       VARCHAR(10)  NOT NULL,
    name       VARCHAR(150) NOT NULL,
    short_name VARCHAR(60)  DEFAULT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_faculty_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 2. DEPARTMENTS ──────────────────────────────────────────
CREATE TABLE departments (
    id         INT          NOT NULL AUTO_INCREMENT,
    faculty_id INT          NOT NULL,
    code       VARCHAR(10)  NOT NULL,
    name       VARCHAR(150) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_dept_code (code),
    KEY fk_dept_faculty (faculty_id),
    CONSTRAINT fk_dept_faculty
        FOREIGN KEY (faculty_id) REFERENCES faculties (id)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 3. MATRIC SERIALS (kept for reference) ─────────────────
CREATE TABLE matric_serials (
    id             INT         NOT NULL AUTO_INCREMENT,
    admission_year CHAR(2)     NOT NULL,
    faculty_code   VARCHAR(10) NOT NULL,
    dept_code      VARCHAR(10) NOT NULL,
    last_serial    INT         NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_serial (admission_year, faculty_code, dept_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 3b. LIBRARY REGISTRATION SERIALS ──────────────────────
--  Auto-increments per calendar year to produce LIB-2025-0001
CREATE TABLE lib_serials (
    id          INT         NOT NULL AUTO_INCREMENT,
    reg_year    CHAR(4)     NOT NULL UNIQUE,   -- e.g. "2025"
    last_serial INT         NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 4. USERS ───────────────────────────────────────────────
CREATE TABLE users (
    id                  INT          NOT NULL AUTO_INCREMENT,
    -- library_reg_number: auto-generated by system (used to log in)
    -- e.g.  LIB-2025-0001
    library_reg_number  VARCHAR(30)  NOT NULL,
    -- school_matric: entered by student from their school ID card
    -- e.g.  U22/FNS/CSC/0042
    school_matric       VARCHAR(30)  DEFAULT NULL,
    -- matric_number kept as alias = library_reg_number for backward compat
    matric_number       VARCHAR(30)  NOT NULL,
    full_name           VARCHAR(120) NOT NULL,
    email               VARCHAR(120) NOT NULL,
    phone               VARCHAR(20)  DEFAULT NULL,
    password_hash       VARCHAR(255) NOT NULL,
    role                ENUM('student','staff','admin') NOT NULL DEFAULT 'student',
    admission_year      CHAR(2)      DEFAULT NULL,
    faculty_id          INT          DEFAULT NULL,
    faculty_code        VARCHAR(10)  DEFAULT NULL,
    faculty_name        VARCHAR(150) DEFAULT NULL,
    dept_id             INT          DEFAULT NULL,
    dept_code           VARCHAR(10)  DEFAULT NULL,
    department_name     VARCHAR(150) DEFAULT NULL,
    level               VARCHAR(10)  DEFAULT NULL,
    matric_serial       INT          DEFAULT NULL,
    status              ENUM('active','suspended','inactive','pending') NOT NULL DEFAULT 'active',
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_lib_reg    (library_reg_number),
    UNIQUE KEY uq_matric     (matric_number),
    UNIQUE KEY uq_email      (email),
    UNIQUE KEY uq_school_mat (school_matric),
    KEY fk_user_faculty (faculty_id),
    KEY fk_user_dept    (dept_id),
    CONSTRAINT fk_user_faculty
        FOREIGN KEY (faculty_id) REFERENCES faculties (id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_user_dept
        FOREIGN KEY (dept_id) REFERENCES departments (id)
        ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 4b. LOGIN ATTEMPTS (rate limiting + lockout) ───────────
--  Tracks failed logins per identifier+IP to block brute force
CREATE TABLE login_attempts (
    id          INT          NOT NULL AUTO_INCREMENT,
    identifier  VARCHAR(100) NOT NULL,   -- matric/lib number used at login
    ip_address  VARCHAR(45)  NOT NULL,
    attempted_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_identifier (identifier),
    KEY idx_ip         (ip_address),
    KEY idx_time       (attempted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 4c. AUDIT LOG ──────────────────────────────────────────
--  Records every significant action for accountability
CREATE TABLE audit_log (
    id          INT          NOT NULL AUTO_INCREMENT,
    user_id     INT          DEFAULT NULL,          -- who did it (NULL = guest)
    user_name   VARCHAR(120) DEFAULT NULL,
    action      VARCHAR(100) NOT NULL,              -- e.g. 'login', 'issue_loan'
    target_type VARCHAR(60)  DEFAULT NULL,          -- e.g. 'loan', 'user', 'book'
    target_id   INT          DEFAULT NULL,
    detail      TEXT         DEFAULT NULL,          -- human-readable description
    ip_address  VARCHAR(45)  DEFAULT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_user   (user_id),
    KEY idx_action (action),
    KEY idx_time   (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 5. BOOKS ───────────────────────────────────────────────
CREATE TABLE books (
    id               INT          NOT NULL AUTO_INCREMENT,
    isbn             VARCHAR(20)  DEFAULT NULL,
    title            VARCHAR(255) NOT NULL,
    author           VARCHAR(200) NOT NULL,
    publisher        VARCHAR(150) DEFAULT NULL,
    pub_year         YEAR         DEFAULT NULL,
    edition          VARCHAR(20)  DEFAULT NULL,
    category         VARCHAR(80)  DEFAULT NULL,
    subject          VARCHAR(100) DEFAULT NULL,
    dept_code        VARCHAR(10)  DEFAULT NULL,
    department_name  VARCHAR(150) DEFAULT NULL,
    total_copies     INT          NOT NULL DEFAULT 1,
    available_copies INT          NOT NULL DEFAULT 1,
    location         VARCHAR(80)  DEFAULT NULL,
    cover_emoji      VARCHAR(10)  NOT NULL DEFAULT '📘',
    cover_color      VARCHAR(10)  NOT NULL DEFAULT '#e8f5ec',
    resource_type    ENUM('physical','digital','both') NOT NULL DEFAULT 'physical',
    digital_url      VARCHAR(500) DEFAULT NULL,
    added_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_isbn (isbn)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 6. LOANS ───────────────────────────────────────────────
CREATE TABLE loans (
    id          INT            NOT NULL AUTO_INCREMENT,
    user_id     INT            NOT NULL,
    book_id     INT            NOT NULL,
    issued_by   INT            DEFAULT NULL,
    borrow_date DATE           NOT NULL,
    due_date    DATE           NOT NULL,
    return_date DATE           DEFAULT NULL,
    status      ENUM('active','returned','overdue','lost') NOT NULL DEFAULT 'active',
    fine_amount DECIMAL(8,2)   NOT NULL DEFAULT 0.00,
    fine_paid   TINYINT(1)     NOT NULL DEFAULT 0,
    notes       TEXT           DEFAULT NULL,
    created_at  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY fk_loan_user   (user_id),
    KEY fk_loan_book   (book_id),
    CONSTRAINT fk_loan_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_loan_book
        FOREIGN KEY (book_id) REFERENCES books (id)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 7. RESERVATIONS ────────────────────────────────────────
CREATE TABLE reservations (
    id          INT      NOT NULL AUTO_INCREMENT,
    user_id     INT      NOT NULL,
    book_id     INT      NOT NULL,
    reserved_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expiry_date DATE     DEFAULT NULL,
    status      ENUM('pending','ready','collected','cancelled','expired') NOT NULL DEFAULT 'pending',
    notified    TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY fk_res_user (user_id),
    KEY fk_res_book (book_id),
    CONSTRAINT fk_res_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_res_book
        FOREIGN KEY (book_id) REFERENCES books (id)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 8. ANNOUNCEMENTS ───────────────────────────────────────
--  NOTE: created_by is a plain INT (no FK) to avoid circular
--        dependency with users during import.
CREATE TABLE announcements (
    id           INT          NOT NULL AUTO_INCREMENT,
    title        VARCHAR(255) NOT NULL,
    body         TEXT         NOT NULL,
    tag          VARCHAR(50)  DEFAULT NULL,
    tag_color    VARCHAR(20)  NOT NULL DEFAULT '#1a5c2e',
    published_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active    TINYINT(1)   NOT NULL DEFAULT 1,
    created_by   INT          DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 9. FINES ───────────────────────────────────────────────
CREATE TABLE fines (
    id         INT          NOT NULL AUTO_INCREMENT,
    loan_id    INT          NOT NULL,
    user_id    INT          NOT NULL,
    amount     DECIMAL(8,2) NOT NULL,
    reason     VARCHAR(150) DEFAULT NULL,
    paid       TINYINT(1)   NOT NULL DEFAULT 0,
    paid_at    TIMESTAMP    NULL DEFAULT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY fk_fine_loan (loan_id),
    KEY fk_fine_user (user_id),
    CONSTRAINT fk_fine_loan
        FOREIGN KEY (loan_id) REFERENCES loans (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_fine_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 10. DIGITAL ACCESS LOG ─────────────────────────────────
CREATE TABLE digital_access_log (
    id          INT       NOT NULL AUTO_INCREMENT,
    user_id     INT       NOT NULL,
    book_id     INT       NOT NULL,
    accessed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address  VARCHAR(45) DEFAULT NULL,
    PRIMARY KEY (id),
    KEY fk_dal_user (user_id),
    KEY fk_dal_book (book_id),
    CONSTRAINT fk_dal_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_dal_book
        FOREIGN KEY (book_id) REFERENCES books (id)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ════════════════════════════════════════════════════════════
--  SEED DATA
-- ════════════════════════════════════════════════════════════

-- ── Faculties ──────────────────────────────────────────────
INSERT INTO faculties (code, name, short_name) VALUES
('FNS', 'Faculty of Natural Sciences',         'Natural Sciences'),
('FAS', 'Faculty of Arts and Social Sciences', 'Arts & Social Sciences'),
('FMS', 'Faculty of Management Sciences',      'Management Sciences'),
('LAW', 'Faculty of Law',                      'Law'),
('FED', 'Faculty of Education',                'Education'),
('FAG', 'Faculty of Agriculture',              'Agriculture'),
('FEN', 'Faculty of Engineering',              'Engineering'),
('FES', 'Faculty of Environmental Sciences',   'Environmental Sciences');

-- ── Departments ────────────────────────────────────────────
-- FNS
INSERT INTO departments (faculty_id, code, name) VALUES
(1, 'CSC', 'Computer Science'),
(1, 'BIO', 'Biology'),
(1, 'CHM', 'Chemistry'),
(1, 'PHY', 'Physics'),
(1, 'MTH', 'Mathematics'),
(1, 'BCH', 'Biochemistry'),
(1, 'MCB', 'Microbiology'),
(1, 'STA', 'Statistics');

-- FAS
INSERT INTO departments (faculty_id, code, name) VALUES
(2, 'ENG', 'English Language'),
(2, 'HIS', 'History & International Studies'),
(2, 'SOC', 'Sociology'),
(2, 'POL', 'Political Science'),
(2, 'MCM', 'Mass Communication'),
(2, 'PHL', 'Philosophy'),
(2, 'ISL', 'Islamic Studies');

-- FMS
INSERT INTO departments (faculty_id, code, name) VALUES
(3, 'ACC', 'Accounting'),
(3, 'BUS', 'Business Administration'),
(3, 'ECO', 'Economics'),
(3, 'MKT', 'Marketing'),
(3, 'BNF', 'Banking & Finance'),
(3, 'PBA', 'Public Administration');

-- LAW
INSERT INTO departments (faculty_id, code, name) VALUES
(4, 'LAD', 'Law');

-- FED
INSERT INTO departments (faculty_id, code, name) VALUES
(5, 'EDU', 'Education'),
(5, 'EDM', 'Educational Management'),
(5, 'GNS', 'General Studies');

-- FAG
INSERT INTO departments (faculty_id, code, name) VALUES
(6, 'AGR', 'Agriculture'),
(6, 'ANS', 'Animal Science'),
(6, 'FST', 'Food Science & Technology');

-- FEN
INSERT INTO departments (faculty_id, code, name) VALUES
(7, 'EEE', 'Electrical Engineering'),
(7, 'CVE', 'Civil Engineering'),
(7, 'MEE', 'Mechanical Engineering'),
(7, 'CHE', 'Chemical Engineering');

-- FES
INSERT INTO departments (faculty_id, code, name) VALUES
(8, 'ARC', 'Architecture'),
(8, 'ETM', 'Estate Management'),
(8, 'URP', 'Urban & Regional Planning'),
(8, 'SUR', 'Surveying & Geo-Informatics');

-- ── Default Admin account ──────────────────────────────────
-- Password is: Admin@1234  (change after first login)
-- Admin logs in with: ADMIN-001
INSERT INTO users (library_reg_number, matric_number, school_matric, full_name, email, password_hash, role, department_name) VALUES
(
    'ADMIN-001',
    'ADMIN-001',
    NULL,
    'Library Administrator',
    'library@ibbul.edu.ng',
    '$2y$12$XtUHLfyXbVZ/BqcBi3pWBejJd/9FqkblhCJrS3rh4RXWf4Vv6WLXm',
    'admin',
    'Library Administration'
);

-- ── Sample Books ───────────────────────────────────────────
INSERT INTO books (isbn, title, author, publisher, pub_year, category, dept_code, department_name, total_copies, available_copies, resource_type, cover_emoji, cover_color) VALUES
('978-0-262-03384-8', 'Introduction to Algorithms',  'Thomas H. Cormen',     'MIT Press',   2022, 'science',    'CSC', 'Computer Science',        5, 3, 'physical', '📘', '#e8f5ec'),
('978-0-13-468599-1', 'Operating System Concepts',   'Silberschatz & Galvin','Wiley',        2021, 'science',    'CSC', 'Computer Science',        4, 2, 'physical', '💻', '#e3f2fd'),
('978-0-07-802215-9', 'Principles of Management',    'Robbins & Coulter',    'McGraw-Hill',  2020, 'management', 'BUS', 'Business Administration',  6, 5, 'both',     '📗', '#e8f0fe'),
('978-978-8510-03-2', 'Nigerian Constitutional Law', 'Akin Ibidapo-Obe',     'Malthouse',    2019, 'law',        'LAD', 'Law',                     3, 1, 'physical', '⚖️', '#fff3e0'),
('978-0-32-196998-4', 'Organic Chemistry',           'Paula Bruice',         'Pearson',      2023, 'science',    'CHM', 'Chemistry',               4, 4, 'physical', '🧪', '#fce4ec'),
('978-0-07-351129-0', 'Economics (19th Ed)',          'Samuelson & Nordhaus', 'McGraw-Hill',  2022, 'management', 'ECO', 'Economics',               5, 3, 'both',     '📈', '#e8f5ec'),
('978-0-435-27102-7', 'Things Fall Apart',           'Chinua Achebe',        'Heinemann',    2001, 'arts',       'ENG', 'English Language',         8, 7, 'digital',  '📜', '#f3e5f5'),
('978-0-13-600030-4', 'Signals and Systems',         'Oppenheim & Willsky',  'Pearson',      2020, 'science',    'EEE', 'Electrical Engineering',   3, 0, 'physical', '⚡', '#e3f2fd'),
('978-978-081-150-5', 'Business Law in Nigeria',     'O.A. Orojo',           'Evans Brothers',2018,'law',        'LAD', 'Law',                     4, 4, 'both',     '📃', '#e8f0fe'),
('978-0-13-421820-1', 'Computer Networks',           'Andrew Tanenbaum',     'Pearson',      2021, 'science',    'CSC', 'Computer Science',        3, 2, 'physical', '🌐', '#e8f5ec');

-- ── Sample Announcements ───────────────────────────────────
INSERT INTO announcements (title, body, tag, tag_color, is_active) VALUES
(
    'Extended Hours During Examination Period',
    'The library will operate from 7am to 11pm Monday to Saturday during the 2024/2025 examination period to support student revision.',
    'Notice', '#1a5c2e', 1
),
(
    'Over 5,000 New E-Books Added to the Portal',
    'New titles across Engineering, Sciences, Law, and Management have been added from leading academic publishers.',
    'New Addition', '#c8960c', 1
),
(
    'Free Research Skills Workshop — Open to All Students',
    'Learn APA 7th edition citations, database usage, and literature review writing. Register at the library desk.',
    'Training', '#1a56a4', 1
);

-- Re-enable FK checks
SET FOREIGN_KEY_CHECKS = 1;
